// <auto-generated />
using System;
using IztekTestCase.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace IztekTestCase.Migrations
{
    [DbContext(typeof(TestDbContext))]
    [Migration("20231105193131_Initial Migration")]
    partial class InitialMigration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.13")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("IztekTestCase.Models.Input", b =>
                {
                    b.Property<Guid>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("input")
                        .HasColumnType("int");

                    b.Property<bool>("isPrime")
                        .HasColumnType("bit");

                    b.HasKey("id");

                    b.ToTable("Inputs");
                });
#pragma warning restore 612, 618
        }
    }
}
